config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'pages/index'
  root 'pages#index'

  get 'pages/clients'
  get 'pages/contact'
  get 'pages/types'
  get 'pages/game'
  get 'pages/invitade'
  get 'pages/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/institution.rb
class Institution < ApplicationRecord
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/premium.rb
class Premium < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   geocoded_by :address
   after_validation :geocode

   enum role: [:admin, :holder, :teacher, :student]
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def after_sign_up_path_for(resource)
  'pages/type' # Or :prefix_to_your_route
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end


end

app/controllers/game_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :execution, :type, :route, :available, :creation)
    end





end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :execution, :type, :route, :available, :creation)
    end
end

app/controllers/geocoder_controller.rb
class GeocoderController < ApplicationController
  def findaddress
    @address = Geocoder.address([params[:latitude], params[:longitude]])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def client
  end

  def contact
  end

  def invitade
  end

  def new
  end

  def type
    @Institutions = Institution.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/geocoder_helper.rb
module GeocoderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def logged?
    session[:user_id].present? ? true : false
  end
end

app/views/layouts/_navbar.html.erb
<%= image_tag 'punta.jpg', :class=>"img-fluid" %>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="pages_path">Mente Pequeña</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <%= link_to current_user.name, edit_user_registration_path %>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <%= link_to('Salir', destroy_user_session_path, :method=>'delete') %>
        </a>
      </li>
      <% else %>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_user_registration_path%>">Registrarse</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_user_session_path%>">Ingresar</a>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mente pequeña</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <%= value %>
    </div>
    <% end %>
    <section>
      <div class="row">
          <div class="col-sm-4 col-md-3 sidenav">
            <a id="clickbuttom" href=" <%=games_path %>" class="list-group-item list-group-item-action">
             ¡JUEGA!
              </a>
            <a href="<%= pages_type_path %> " class="list-group-item list-group-item-action list-group-item-primary"> Instituciones </a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-secondary"> Random </a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-success">Nosotros</a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-danger">Mision</a>
            <a href="#" class="list-group-item list-group-item-action list-group-item-warning">Preguntas Frecuentes</a>
            <a href=" <%= pages_client_path %>" class="list-group-item list-group-item-action list-group-item-info">Colaboracion </a>
            <a href=" <%= pages_contact_path %>" class="list-group-item list-group-item-action list-group-item-light">Contacto</a>
            <a href=" <%= pages_new_path %> " class="list-group-item list-group-item-action list-group-item-dark">Noticias</a>
        </div>
        <div class="col-md-6">
          <%= yield %>
        </div>
      </div>
      <footer class="container-fluid bg-primary text-white p-5">
         <a href="https://github.com/palomagabic" class="text-white"><i class="fab fa-github fa-3x" data-toggle="tooltip" data-placement="left" title="Github"></i></a>
         Creado por Paloma Cortes Lazo</footer>
    </section>
  </body>
</html>

app/views/pages/client.html.erb
<h1>Pages#client</h1>
<p>Find me in app/views/pages/client.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/invitade.html.erb
<h1>Pages#invitade</h1>
<p>Find me in app/views/pages/invitade.html.erb</p>

app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

app/views/pages/type.html.erb
<h1>Pages#type</h1>
<p>Find me in app/views/pages/type.html.erb</p>